export type MockServerData = {
  id: string[];
  title: string[];
  description:string[];
  date : string[];
  name : string[];
  latitude : number[];
  longitude : number[];
  previewImage : string[];
  images : string[];
  isPremium : boolean[];
  isFavorite : boolean[];
  rating : number[];
  categories : string[];
  bedrooms : number[];
  maxAdults : number[];
  price : number[];
  goods : string[];
  nameHost : string[];
  email : string[];
  avatarUrl : string[];
  isPro : boolean[];
  password : string[];
  comments : number[];
  latitudeCard : number[];
  longitudeCard : number[];
};
